ALTER TABLE income ADD COLUMN cheque_no VARCHAR(100) DEFAULT NULL, ADD COLUMN cheque_date DATE DEFAULT NULL;
ALTER TABLE expenses ADD COLUMN cheque_no VARCHAR(100) DEFAULT NULL, ADD COLUMN cheque_date DATE DEFAULT NULL;
