ALTER TABLE referral_payment
 ADD COLUMN payment_mode VARCHAR(50) NOT NULL DEFAULT 'Cash',
 ADD COLUMN cheque_no VARCHAR(100) DEFAULT NULL,
 ADD COLUMN cheque_date DATE DEFAULT NULL,
 ADD COLUMN attachment VARCHAR(255) DEFAULT NULL,
 ADD COLUMN attachment_name VARCHAR(255) DEFAULT NULL;
